var quizes2 = ["html", "css", "javascript", "phyton", "flutter"];

Map<String, dynamic> questions2 = {
  "english": {
    "html": [
      {
        "question": "Write a Hello World inside a Paragraph Tag in HTML",
        "hint": "It starts with <p>",
        "codebox1": "",
        "codebox2": "",
        "anwser": "<p>Hello World</p>",
      },
      {
        "question": "Write a Button Tag that says 'Click me' in HTML",
        "hint": "It ends with </button>",
        "codebox1": "",
        "codebox2": "",
        "anwser": "<button>Click me</button>",
      },
      {
        "question": "Write a h1 Tag that says 'Header' in HTML",
        "hint": "You should start with <h1>",
        "codebox1": "",
        "codebox2": "",
        "anwser": "<h1>Header</h1>",
      },
      {
        "question": "Write a Empty Div Tag in HTML",
        "hint": "You should end it with </div>",
        "codebox1": "",
        "codebox2": "",
        "anwser": "<div></div>",
      },
      {
        "question": "Write a HyperLink Tag that says 'Go to site' in HTML",
        "hint": "It starts with <a>",
        "codebox1": "",
        "codebox2": "",
        "anwser": "<a>Go to site</a>",
      },
      {
        "question": "Write ONE empty item for this list in HTML",
        "hint": "It starts with <li>",
        "codebox1": "<ul>",
        "codebox2": "</ul>",
        "anwser": "<li></li>",
      },
      {
        "question": "Import the JavaScript file called 'script.js' to HTML",
        "hint": "It starts with 'src='",
        "codebox1": "<script",
        "codebox2": "</script>",
        "anwser": 'src="script.js">',
      },
    ],
    "css": [
      {
        "question": "Paint this Button letters Red in CSS",
        "hint": "You should start with 'color:' ",
        "codebox1": "button{",
        "codebox2": "}",
        "anwser": "color:red",
      },
      {
        "question": "Paint this Div background-color green in CSS",
        "hint": "You should start with 'background-color:' ",
        "codebox1": "div{",
        "codebox2": "}",
        "anwser": "background-color:green",
      },
      {
        "question": "Change this h1 font-weight to bold in CSS",
        "hint": "You should start with 'font-weight:' ",
        "codebox1": "h1{",
        "codebox2": "}",
        "anwser": "font-weight:bold",
      },
      {
        "question": "Change this box height to 100px in CSS",
        "hint": "You should start with 'height:' ",
        "codebox1": "#box{",
        "codebox2": "}",
        "anwser": "height:100px",
      },
      {
        "question": "Change the display type of this div to flex in CSS",
        "hint": "You should start with 'display:' ",
        "codebox1": "div{",
        "codebox2": "}",
        "anwser": "display:flex",
      },
      {
        "question": "Remove the text-decoration of this li in CSS",
        "hint": "You should start with 'text-decoration:' ",
        "codebox1": "li{",
        "codebox2": "}",
        "anwser": "text-decoration:none",
      },
      {
        "question": "Define a margin-top of 100px to this box in CSS",
        "hint": "You should start with 'margin-top:' ",
        "codebox1": "#box{",
        "codebox2": "}",
        "anwser": "margin-top:100px",
      },
    ],
    "javascript": [
      {
        "question": "Declare a var called number with the value of 5 in Javascript",
        "hint": "You should start using the keyword 'var'",
        "codebox1": "",
        "codebox2": "",
        "anwser": "var number=5",
      },
      {
        "question": "Print the var number value in this function in JavaScript",
        "hint": "You should start with 'console.log' ",
        "codebox1": "function(){",
        "codebox2": "}",
        "anwser": "console.log(number)",
      },
      {
        "question": "Compare the value of this two variables in JavaScript",
        "hint": "You should use the equality operator",
        "codebox1": "number",
        "codebox2": "number2",
        "anwser": "==",
      },
      {
        "question": "Create a condition to check if the var number is greater than the var number2",
        "hint": "You should use the greater operator",
        "codebox1": "if(",
        "codebox2": ")",
        "anwser": "number>number2",
      },
      {
        "question": "Create a for loop for a maximum of 5 in JavaScript",
        "hint": "You should start with 'for' ",
        "codebox1": "",
        "codebox2": "",
        "anwser": "for(var i=0; i<5; i++)",
      },
      {
        "question": "Create a new div tag in the DOM with Javascript",
        "hint": "You should start with 'document.createElement' ",
        "codebox1": "",
        "codebox2": "",
        "anwser": 'document.createElement("div")',
      },
      {
        "question": "Select the bigText class in the DOM with Javascript",
        "hint": "You should start with 'document.querySelector' ",
        "codebox1": "",
        "codebox2": "",
        "anwser": 'document.querySelector(.bigText)',
      },
    ],
    "phyton": [
      {
        "question": "Declare a var called number with the value of 10 in Phyton",
        "hint": "You DON'T need to used keywords like 'var'",
        "codebox1": "",
        "codebox2": "",
        "anwser": "number=10",
      },
      {
        "question": "Print the var called number in Phyton",
        "hint": "You should use the print() function",
        "codebox1": "def func():",
        "codebox2": "",
        "anwser": "print(number)",
      },
      {
        "question": "Create a function called func() in Phyton",
        "hint": "It's the same function of the last exercise",
        "codebox1": "",
        "codebox2": "print(number)",
        "anwser": "def func():",
      },
      {
        "question": "Create a while lop for the condition of i being minor than 10 in Phyton",
        "hint": "You should use the while keyword",
        "codebox1": "",
        "codebox2": "print(i)",
        "anwser": "while i < 10:",
      },
      {
        "question": "Create a for loop for a maximum of 10 in Phyton",
        "hint": "You should use the for keyword",
        "codebox1": "",
        "codebox2": "",
        "anwser": "for i in range(10)",
      },
      {
        "question": "Create a if statement to check if the var x is greater than the var y",
        "hint": "You should use the if keyword",
        "codebox1": "",
        "codebox2": 'print("x is bigger than y")',
        "anwser": "if x > y:",
      },
    ],
    "flutter": [
      {
        "question": "Declare a int called number with the value of 15 in Dart",
        "hint": "You should start using the keyword 'int'",
        "codebox1": "",
        "codebox2": "",
        "anwser": "int number=5",
      },
      {
        "question": "Print the var called number in Dart",
        "hint": "You should use the print() function",
        "codebox1": "void printNumber(){",
        "codebox2": "}",
        "anwser": "print(number)",
      },
      {
        "question": "Create a Text Widget with 'Hello World' inside it in Flutter",
        "hint": "You need to use the Text() widget",
        "codebox1": "Container(child:",
        "codebox2": ")",
        "anwser": 'Text("Hello World")',
      },
      {
        "question": "Define the backgroundColor of this AppBar to red",
        "hint": "You should use the backgroundColor property",
        "codebox1": "AppBar(",
        "codebox2": ")",
        "anwser": "backgroundColor:Colors.red",
      },
      {
        "question": "Create a SizedBox with the height of 100",
        "hint": "You have to use the SizedBox widget",
        "codebox1": "",
        "codebox2": "",
        "anwser": "SizedBox(height:100)",
      },
      {
        "question": "Change the size of this Text font to 30",
        "hint": "You have to use the fontSize property",
        "codebox1": "TextStyle(",
        "codebox2": ")",
        "anwser": "fontSize:30",
      },
      {
        "question": "Define this ListView to allow shrinkWrap",
        "hint": "You have to use the shinkWrap property",
        "codebox1": "ListView(",
        "codebox2": ")",
        "anwser": "shrinkWrap:true",
      },
    ]
  },
  "portuguese": {
    "html": [
      {
        "question": "Escreva um 'Hello World' dentro de uma tag de Parágrafo em HTML",
        "hint": "Inicie com <p>",
        "codebox1": "",
        "codebox2": "",
        "anwser": "<p>Hello World</p>",
      },
      {
        "question": "Escreva uma tag de botão que diga 'Clique em mim' em HTML",
        "hint": "Comece com </button>",
        "codebox1": "",
        "codebox2": "",
        "anwser": "<button>Clique em mim</button>",
      },
      {
        "question": "Escreva uma tag h1 que diga 'Cabeçalho' em HTML",
        "hint": "Comece com <h1>",
        "codebox1": "",
        "codebox2": "",
        "anwser": "<h1>Cabeçalho</h1>",
      },
      {
        "question": "Escreva uma Div vazia em HTML",
        "hint": "Termine com </div>",
        "codebox1": "",
        "codebox2": "",
        "anwser": "<div></div>",
      },
      {
        "question": "Escreva uma tag de link que diga 'Ir para o site' em HTML",
        "hint": "Inicie com <a>",
        "codebox1": "",
        "codebox2": "",
        "anwser": "<a>Ir para o site</a>",
      },
      {
        "question": "Escreva UM item vazio para esta lista em HTML",
        "hint": "Comece com <li>",
        "codebox1": "<ul>",
        "codebox2": "</ul>",
        "anwser": "<li></li>",
      },
      {
        "question": "Importe o arquivo JavaScript chamado 'script.js' para seu arquivo HTML",
        "hint": "Tente começar com 'src='",
        "codebox1": "<script",
        "codebox2": "</script>",
        "anwser": 'src="script.js">',
      },
    ],
    "css": [
      {
        "question": "Pinte as letras deste botão de vermelho em CSS",
        "hint": "Tente começar com 'color:' ",
        "codebox1": "button{",
        "codebox2": "}",
        "anwser": "color:red",
      },
      {
        "question": "Pinte a cor de fundo dessa Div pra verde em CSS",
        "hint": "Tente começar com 'background-color:' ",
        "codebox1": "div{",
        "codebox2": "}",
        "anwser": "background-color:green",
      },
      {
        "question": "Altere o peso da fonte desta tag h1 para NEGRITO em CSS",
        "hint": "Tente começar com 'font-weight:' ",
        "codebox1": "h1{",
        "codebox2": "}",
        "anwser": "font-weight:bold",
      },
      {
        "question": "Altere a altura desta caixa para 100px em CSS ",
        "hint": "Comece com 'height:' ",
        "codebox1": "#caixa{",
        "codebox2": "}",
        "anwser": "height:100px",
      },
      {
        "question": "Altere o display type desta Div pra flex em CSS",
        "hint": "Tente iniciar com 'display:' ",
        "codebox1": "div{",
        "codebox2": "}",
        "anwser": "display:flex",
      },
      {
        "question": "Remova a decoração de texto deste li em CSS",
        "hint": "Comece com 'text-decoration:' ",
        "codebox1": "li{",
        "codebox2": "}",
        "anwser": "text-decoration:none",
      },
      {
        "question": "Defina uma margin-top de 100px para essa caixa em CSS",
        "hint": "Inicie com 'margin-top:' ",
        "codebox1": "#caixa{",
        "codebox2": "}",
        "anwser": "margin-top:100px",
      },
    ],
    "javascript": [
      {
        "question": "Declare uma variável chamada 'numero' com o valor de 5 em Javascript",
        "hint": "Tente começar usando a palavra-chave 'var'",
        "codebox1": "",
        "codebox2": "",
        "anwser": "var numero=5",
      },
      {
        "question": "Printe o valor da variável 'numero' nessa função JavaScript",
        "hint": "Use o 'console.log' ",
        "codebox1": "function(){",
        "codebox2": "}",
        "anwser": "console.log(numero)",
      },
      {
        "question": "Compare o valor dessas duas variáveis em JavaScript",
        "hint": "Use o operador de igualdade",
        "codebox1": "numero",
        "codebox2": "numero2",
        "anwser": "==",
      },
      {
        "question": "Crie uma condição pra checar se a variável numero que a variável numero2",
        "hint": "Use o operador de 'Maior que'",
        "codebox1": "if(",
        "codebox2": ")",
        "anwser": "numero>numero2",
      },
      {
        "question": "Crie um loop for pra um máximo de 5 em JavaScript",
        "hint": "Comece com 'for' ",
        "codebox1": "",
        "codebox2": "",
        "anwser": "for(var i=0; i<5; i++)",
      },
      {
        "question": "Crie uma nova tag div no DOM usando JavaScript",
        "hint": "Tente usar o 'document.createElement' ",
        "codebox1": "",
        "codebox2": "",
        "anwser": 'document.createElement("div")',
      },
      {
        "question": "Selecione a classe textoGrande no DOM usando Javascript",
        "hint": "Inicie com 'document.querySelector' ",
        "codebox1": "",
        "codebox2": "",
        "anwser": 'document.querySelector(.textoGrande)',
      },
    ],
    "phyton": [
      {
        "question": "Declare uma variável chamada 'numero' com o valor de 10 em Phyton",
        "hint": "NÃO é necessário usar palavras-chaves como 'var'",
        "codebox1": "",
        "codebox2": "",
        "anwser": "numero=10",
      },
      {
        "question": "Printe a variável chamada numero em Phyton",
        "hint": "Use a função print()",
        "codebox1": "def func():",
        "codebox2": "",
        "anwser": "print(numero)",
      },
      {
        "question": "Crie a função chamada 'func' em Phyton",
        "hint": "É a mesma função do último exercício",
        "codebox1": "",
        "codebox2": "print(numero)",
        "anwser": "def func():",
      },
      {
        "question": "Crie um loop while para a condição de i ser menor que 10 em Phyton",
        "hint": "Use a palavra-chave while",
        "codebox1": "",
        "codebox2": "print(i)",
        "anwser": "while i < 10:",
      },
      {
        "question": "Crie um loop for para um máximo de 10 em Phyton",
        "hint": "Use a palavra-chave for",
        "codebox1": "",
        "codebox2": "",
        "anwser": "for i in range(10)",
      },
      {
        "question": "Crie uma condição if para verificar se a var x é maior que a var y",
        "hint": "Use a palavra-chave if",
        "codebox1": "",
        "codebox2": 'print("x é maior que y")',
        "anwser": "if x > y:",
      },
    ],
    "flutter": [
      {
        "question": "Declare um int chamado numero com o valor de 15 no Dart",
        "hint": "Inicie com a palavra-chave 'int'",
        "codebox1": "",
        "codebox2": "",
        "anwser": "int numero=5",
      },
      {
        "question": "Printe a variável calada numero em Dart",
        "hint": "Use a função print()",
        "codebox1": "void printNumber(){",
        "codebox2": "}",
        "anwser": "print(numero)",
      },
      {
        "question": "Crie um widget de texto com 'Hello World' dentro dele no Flutter",
        "hint": "É necessário usar o widget Text()",
        "codebox1": "Container(child:",
        "codebox2": ")",
        "anwser": 'Text("Hello World")',
      },
      {
        "question": "Defina a cor de fundo deste AppBar para vermelho",
        "hint": "Você deve usar a propriedade backgroundColor",
        "codebox1": "AppBar(",
        "codebox2": ")",
        "anwser": "backgroundColor:Colors.red",
      },
      {
        "question": "Crie um SizedBox com a altura de 100",
        "hint": "Você tem que usar a propriedade height",
        "codebox1": "",
        "codebox2": "",
        "anwser": "SizedBox(height:100)",
      },
      {
        "question": "Mude o tamanho da fonte desse texto pra 30",
        "hint": "Você tem que usar a propriedade fontSize",
        "codebox1": "TextStyle(",
        "codebox2": ")",
        "anwser": "fontSize:30",
      },
      {
        "question": "Defina esta ListView para permitir o shrinkWrap",
        "hint": "Você tem que usar a propriedade shinkWrap",
        "codebox1": "ListView(",
        "codebox2": ")",
        "anwser": "shrinkWrap:true",
      },
    ]
  }
};
