Map<String, dynamic> strings = {
  "english": {
    "progedu": "/ProgEdu",
    "c1": "Challenge 1 - Quiz",
    "c2": "Challenge 2 - Pratical Exercices",
    "c3": "Challenge 3 - Coming Soon",
    "exercice": "exercice",
    "question": "question",
    "hint": "Hint:",
    "right": "You are right!",
    "wrong": "You are wrong!...",
    "input": "Your input:",
    "rightanwser": "The anwser is:",
    "youranwser": "Type your anwser...",
    "submit": "Submit",
    "hello": "Hello",
    "challenge": "What challenge you wanna play?",
    "error": "Something went wrong",
    "concluded": "concluded",
    "sent": "Email sent, remember to check your spam box",
    "send": "Send email to reset password",
    "email": "Type your email...",
    "password": "Type your password...",
    "reset": "Reset Password",
    "emptyboth": "One or more fields are empty",
    "welcome": "Welcome back!",
    "forgotpassword": "Forgot your password?",
    "noaccount": "Don't have an account yet?",
    "sign": " Sign in",
    "emptyname": "Type your nickname...",
    "name": "What's your nickname?",
    "choosename": "Choose nickname",
    "learncode": "Challenge your coding skills now!",
    "register": "Register",
    "hasaccount": "Already has an account?",
    "quizranking": "Quiz Rankings",
    "exerciceranking": "Exercice Rankings",
    "selectranking": "SELECT A RANKING",
    "exit": "Are you sure you want to exit?",
    "login": " Login",
    "logout": "You will logout and return to main screen.",
    "exitconfirm": "Exit"
  },
  "portuguese": {
    "progedu": "/ProgEdu",
    "c1": "Desafio 1 - Quiz",
    "c2": "Desafio 2 - Exercícios Práticos",
    "c3": "Desafio 3 - Em breve",
    "exercice": "exercício",
    "question": "questão",
    "hint": "Dica:",
    "right": "Você acertou!",
    "wrong": "Você errou...",
    "input": "Sua resposta:",
    "rightanwser": "A resposta é:",
    "youranwser": "Digite sua resposta...",
    "submit": "Responder",
    "hello": "Olá",
    "challenge": "Qual desafio você quer jogar?",
    "error": "Alguma coisa deu errado",
    "concluded": "concluído",
    "sent": "Email enviado, lembre-se de checar sua caixa de spam",
    "send": "Enviar email para recuperar senha",
    "email": "Digite seu email...",
    "password": "Digite sua senha...",
    "reset": "Recuperar senha",
    "emptyboth": "Um ou mais campos estão vazios",
    "welcome": "Bem vindo de volta!",
    "forgotpassword": "Esqueceu sua senha?",
    "noaccount": "Ainda não tem uma conta?",
    "sign": " Registrar-se",
    "emptyname": "Digite seu nome...",
    "name": "Qual seu nome?",
    "choosename": "Escolher nome",
    "learncode": "Teste suas habilidades de programação!",
    "register": "Registrar",
    "hasaccount": "Já tem uma conta?",
    "quizranking": "Rankings do Quiz",
    "exerciceranking": "Rankings do Exercício Prático",
    "selectranking": "SELECIONAR UM RANKING",
    "exit": "Tem certeza que quer sair?",
    "login": " Entrar",
    "logout": "Você será desconectado e voltará ao menu principal.",
    "exitconfirm": "Sair"
  }
};
